# Generated by Django 5.2.9 on 2026-01-06 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.IntegerField(unique=True, verbose_name='Sıra No')),
                ('firma', models.CharField(choices=[('YAGCILAR', 'YAĞCILAR'), ('TEPEKUM', 'TEPEKUM'), ('NAMDAR', 'NAMDAR'), ('SEKER', 'ŞEKER'), ('AKOVA', 'AKOVA'), ('KOOP', 'KOOP.'), ('NAZILLI', 'NAZİLLİ')], max_length=20, verbose_name='Firma/Şube')),
                ('urun', models.CharField(choices=[('MOTORIN', 'MOTORİN'), ('BENZIN', 'BENZİN')], max_length=20, verbose_name='Ürün')),
                ('litre', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Litre')),
                ('tl', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TL (Litre × Alış Fiyatı)')),
                ('odeme_turu', models.CharField(blank=True, choices=[('DBS', 'DBS'), ('NAKIT', 'NAKİT'), ('KK', 'K.K')], max_length=10, null=True, verbose_name='Ödeme Türü')),
                ('bos_alan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Boş Alan (Sonra Doldurulacak)')),
                ('onay', models.BooleanField(default=False, verbose_name='Onay/Ekle')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['sira_no'],
            },
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.IntegerField(unique=True, verbose_name='Sıra No')),
                ('kime', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kime Ödeme Yapılacak')),
                ('ne_kadar', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ne Kadar')),
                ('onay', models.BooleanField(default=False, verbose_name='Onay')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['sira_no'],
            },
        ),
        migrations.CreateModel(
            name='Tahsilat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.IntegerField(unique=True, verbose_name='Sıra No')),
                ('kime', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kime Ödeme Yapılacak')),
                ('ne_kadar', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ne Kadar')),
                ('onay', models.BooleanField(default=False, verbose_name='Onay')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Tahsilat',
                'verbose_name_plural': 'Tahsilatlar',
                'ordering': ['sira_no'],
            },
        ),
        migrations.CreateModel(
            name='Tanker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.IntegerField(unique=True, verbose_name='Sıra No')),
                ('tanker_adi', models.CharField(max_length=100, verbose_name='Tanker Adı/Soyadı')),
                ('cekici_plaka', models.CharField(blank=True, max_length=20, null=True, verbose_name='Çekici Plaka')),
                ('dorse_plaka', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dorse Plaka')),
                ('goz_1', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='1. Göz Kapasitesi (Litre)')),
                ('goz_2', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2. Göz Kapasitesi (Litre)')),
                ('goz_3', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='3. Göz Kapasitesi (Litre)')),
                ('goz_4', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='4. Göz Kapasitesi (Litre)')),
                ('goz_5', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='5. Göz Kapasitesi (Litre)')),
                ('toplam_goz_kapasitesi', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Toplam Göz Kapasitesi (Litre)')),
                ('toplam_tasima_kapasitesi', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Toplam Taşıma Kapasitesi (Litre)')),
                ('aktif', models.BooleanField(default=False, verbose_name='Aktif (Bugün Kullanılacak)')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Tanker',
                'verbose_name_plural': 'Tankerler',
                'ordering': ['sira_no'],
            },
        ),
        migrations.CreateModel(
            name='AlisFiyati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sube', models.CharField(choices=[('YAGCILAR', 'YAĞCILAR'), ('TEPEKUM', 'TEPEKUM'), ('NAMDAR', 'NAMDAR'), ('SEKER', 'ŞEKER'), ('AKOVA', 'AKOVA'), ('KOOP', 'KOOP.'), ('NAZILLI', 'NAZİLLİ')], max_length=20, verbose_name='Şube')),
                ('urun', models.CharField(choices=[('MOTORIN', 'MOTORİN'), ('BENZIN', 'BENZİN')], max_length=20, verbose_name='Ürün')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alış Fiyatı (TL)')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Alış Fiyatı',
                'verbose_name_plural': 'Alış Fiyatları',
                'ordering': ['sube', 'urun'],
                'unique_together': {('sube', 'urun')},
            },
        ),
        migrations.CreateModel(
            name='BenzinSatis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('sube', models.CharField(choices=[('YAGCILAR', 'YAĞCILAR'), ('TEPEKUM', 'TEPEKUM'), ('NAMDAR', 'NAMDAR'), ('SEKER', 'ŞEKER'), ('AKOVA', 'AKOVA'), ('KOOP', 'KOOP.'), ('NAZILLI', 'NAZİLLİ')], max_length=20, verbose_name='Şube')),
                ('deger', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Satış Değeri')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Benzin Satış',
                'verbose_name_plural': 'Benzin Satışları',
                'ordering': ['-tarih', 'sube'],
                'unique_together': {('tarih', 'sube')},
            },
        ),
        migrations.CreateModel(
            name='MotorinSatis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('sube', models.CharField(choices=[('YAGCILAR', 'YAĞCILAR'), ('TEPEKUM', 'TEPEKUM'), ('NAMDAR', 'NAMDAR'), ('SEKER', 'ŞEKER'), ('AKOVA', 'AKOVA'), ('KOOP', 'KOOP.'), ('NAZILLI', 'NAZİLLİ')], max_length=20, verbose_name='Şube')),
                ('deger', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Satış Değeri')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Motorin Satış',
                'verbose_name_plural': 'Motorin Satışları',
                'ordering': ['-tarih', 'sube'],
                'unique_together': {('tarih', 'sube')},
            },
        ),
    ]
