# Generated by Django 5.2.9 on 2026-01-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_alisfiyati_id_alter_benzinsatis_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AracBilgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.IntegerField(unique=True, verbose_name='Sıra No')),
                ('firma', models.CharField(blank=True, max_length=200, null=True, verbose_name='Firma')),
                ('sofor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Şoför')),
                ('tc', models.CharField(blank=True, max_length=11, null=True, verbose_name='T.C')),
                ('dorse', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dorse')),
                ('cekici', models.CharField(blank=True, max_length=50, null=True, verbose_name='Çekici')),
                ('goz_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='1. Göz')),
                ('goz_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='2. Göz')),
                ('goz_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='3. Göz')),
                ('goz_4', models.CharField(blank=True, max_length=50, null=True, verbose_name='4. Göz')),
                ('goz_5', models.CharField(blank=True, max_length=50, null=True, verbose_name='5. Göz')),
                ('goz_6', models.CharField(blank=True, max_length=50, null=True, verbose_name='6. Göz')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Araç Bilgi',
                'verbose_name_plural': 'Araç Bilgileri',
                'ordering': ['sira_no'],
            },
        ),
        migrations.DeleteModel(
            name='Aygaz',
        ),
        migrations.DeleteModel(
            name='Hypco',
        ),
    ]
