# Generated by Django 5.2.9 on 2026-01-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20260108_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='aracbilgi',
            name='tasima_siniri_lt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Taşıma Sınırı Lt'),
        ),
        migrations.AddField(
            model_name='aracbilgi',
            name='toplam_litre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Toplam Litre'),
        ),
    ]
