# Generated by Django 5.2.9 on 2026-01-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_aracbilgi_tasima_siniri_lt_aracbilgi_toplam_litre'),
    ]

    operations = [
        migrations.AddField(
            model_name='aracbilgi',
            name='aktif',
            field=models.BooleanField(default=False, verbose_name='Aktif'),
        ),
    ]
