# Generated by Django 5.2.9 on 2026-01-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_urun'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.IntegerField(unique=True, verbose_name='Sıra No')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Menü Adı (Kod)')),
                ('baslik', models.CharField(max_length=100, verbose_name='Başlık (Türkçe)')),
                ('icon', models.CharField(default='⛽', max_length=10, verbose_name='İkon (Emoji)')),
                ('page_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayfa URL')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Menü Öğesi',
                'verbose_name_plural': 'Menü Öğeleri',
                'ordering': ['sira_no'],
            },
        ),
    ]
