# Generated by Django 5.2.9 on 2026-01-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='tab_baslik',
            field=models.CharField(blank=True, help_text="Tab'da görünecek başlık (boşsa baslik kullanılır)", max_length=100, null=True, verbose_name='Tab Başlığı'),
        ),
    ]
