# Generated by Django 5.2.9 on 2026-01-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_menuitem_baslangic_verisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='sube',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Şube'),
        ),
    ]
