# Generated by Django 5.2.9 on 2026-01-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_firma_sube'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvrakTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Evrak Türü')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Evrak Türü',
                'verbose_name_plural': 'Evrak Türleri',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='FirmaEvrak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='firma_evraklari/', verbose_name='Dosya')),
                ('aciklama', models.CharField(blank=True, default='', max_length=200, verbose_name='Açıklama')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('uyari_gunu', models.IntegerField(default=7, verbose_name='Uyarı Günü')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('evrak_turu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evraklar', to='dashboard.evrakturu', verbose_name='Evrak Türü')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evraklar', to='dashboard.firma', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Firma Evrakı',
                'verbose_name_plural': 'Firma Evrakları',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
