# Generated by Django 5.2.9 on 2026-01-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_evrakturu_firmaevrak'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='adres',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='firma',
            name='eposta',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-posta'),
        ),
        migrations.AddField(
            model_name='firma',
            name='telefon',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='firma',
            name='vergi_dairesi',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='firma',
            name='vergi_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Vergi No'),
        ),
        migrations.AddField(
            model_name='firma',
            name='yetkili_kisi',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Yetkili Kişi'),
        ),
    ]
