# Generated by Django 5.2.9 on 2026-01-19 00:00

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_sube'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZamIndirimGunluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(unique=True, verbose_name='Tarih')),
                ('benzin_usd_ton', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, validators=[MinValueValidator(0)], verbose_name='Benzin USD/Ton')),
                ('motorin_usd_ton', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, validators=[MinValueValidator(0)], verbose_name='Motorin USD/Ton')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Zam/İndirim Günlük',
                'verbose_name_plural': 'Zam/İndirim Günlükleri',
                'ordering': ['-tarih'],
            },
        ),
    ]
