# Generated by Django 5.2.9 on 2026-01-19 00:01

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_zam_indirim_gunluk'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamindirimgunluk',
            name='usdtry_1530',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, validators=[MinValueValidator(0)], verbose_name='USD/TRY 15:30'),
        ),
    ]
